Add RateLimitTransport and its documentation
UniAlteri/sellsy-client pull request #31
Opened 2023-03-08 10:47 UTC by juherr

As requested in #30, I propose a documentation update to manage the API rate limit.

I added the implementation as optional too.

Feel free to edit the change :)

2023-03-13 19:21 UTC, frenchcomp commented
Thanks, I had write some comments in my review. Tests are really mandatory.
You're welcome.

2023-03-14 16:57 UTC, juherr commented
@fdglefevre I don't see any comment: I think you didn't finish the review.
Any idea about how to test it?

2023-03-14 16:59 UTC, frenchcomp requested changes

2023-03-14 16:59 UTC, frenchcomp commented on .gitignore
> +composer.phar
This is must be in your global gitignore and not in the project's gitignore

2023-03-14 16:59 UTC, frenchcomp commented on src/Transport/RateLimitTransport.php
> +<?php
If it is a part of documentation, this class must be in documentation folder.
Else tests with PHPUnit are mandatories

2023-03-14 16:59 UTC, frenchcomp commented on src/Transport/RateLimitTransport.php
> +            $stop = microtime(true);
PHP's base functions must be add below `use` class with `use function`

2023-03-14 16:59 UTC, frenchcomp commented on src/Transport/RateLimitTransport.php
> +class RateLimitTransport implements TransportInterface
Specify that this class has a blocking behavior because it use sleep

2023-03-14 17:00 UTC, frenchcomp commented
Sorry, I lost to finish the review :/

2023-03-28 09:41 UTC, juherr commented on src/Transport/RateLimitTransport.php
> +<?php
Tests done

2023-03-28 09:41 UTC, juherr commented on src/Transport/RateLimitTransport.php
> +class RateLimitTransport implements TransportInterface
Done

2023-03-28 09:41 UTC, juherr commented on src/Transport/RateLimitTransport.php
> +            $stop = microtime(true);
Done

2023-04-02 14:05 UTC, merged

2023-04-02 14:18 UTC, frenchcomp commented
It's merged. Thanks you